image: mcr.microsoft.com/dotnet/sdk:3.1

stages:
  - build-test
  - deploy

Build And Test:
  stage: build-test
  script:
    - dotnet restore
    - dotnet build
    - dotnet test --verbosity d

deploy:
  stage: deploy
  only:
    - tags
  script:
    - dotnet restore
    - dotnet pack -c Release /p:Version=$CI_COMMIT_TAG
    - dotnet nuget push "RecipeScraper/bin/Release/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
