image: mcr.microsoft.com/dotnet/sdk:3.1

stages:
  - build
  - deploy

Build:
  stage: build
  script:
    - dotnet restore
    - dotnet build

deploy:
  stage: deploy
  only:
    - tags
  script:
    - dotnet restore
    - dotnet pack -c Release /p:Version=$CI_COMMIT_TAG
    - dotnet nuget push "bin/Release/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
