name: release

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish-nuget:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Install dependencies
      run: dotnet restore
    - name: Pack
      run: dotnet pack --configuration Release RecipeScraper/RecipeScraper.csproj --output . /p:Version=${VERSION}
    - name: PushNuget
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
